### PR TITLE
create container.yaml for odcs multi-arch build

### PR DESCRIPTION
**Pull request by jeffdyoung**
create container.yaml for odcs multi-arch build
@dorzel @adammhaile Please review.

### CODE REVIEW

**Comment by adammhaile** [comment]
+1

**Comment by dorzel** [comment]
+1

**Comment by jeffdyoung** [comment]
@aveshagarwal @ravisantoshgudimetla  Is this ok to merge? We need to get this in, so @adammhaile can enable ppc64le builds for OCP. Thanks!

**Comment by aveshagarwal** [comment]
/lgtm

Thought have you looked into why e2e are failing?

**Comment by jeffdyoung** [comment]
Dropping this. We won't be doing odcs builds in the near future. Thanks!

**Pull request closed without merging**
