### PR TITLE
Pull upstream changes in from v0.10

### PR DESCRIPTION
**Pull request by damemi**
This contains critical fixes and updates from the upstream sigs.k8s.io/descheduler repo. These changes were pulled by `git pull upstream master` and resolving conflicts in Readme, .travis.yaml, and Makefiles.

### CODE REVIEW

**Comment by damemi** [comment]
@ingvagabund now that we sorted out the image building problem I (thought I) saw, this is ready for review, and I've tested it locally

**Comment by ingvagabund** [comment]
Building quay.io/jchaloup/descheduler:debug-20200401 from the PR head:
```
$ oc describe pod cluster-56c87cf765-jpqh4 -n openshift-kube-descheduler-operator
Name:                 cluster-56c87cf765-jpqh4
Namespace:            openshift-kube-descheduler-operator
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 ip-10-0-171-235.us-east-2.compute.internal/10.0.171.235
Start Time:           Wed, 01 Apr 2020 19:08:34 +0200
Labels:               app=descheduler
                      pod-template-hash=56c87cf765
Annotations:          k8s.v1.cni.cncf.io/networks-status:
                        [{
                            "name": "openshift-sdn",
                            "interface": "eth0",
                            "ips": [
                                "10.131.0.19"
                            ],
                            "dns": {},
                            "default-route": [
                                "10.131.0.1"
                            ]
                        }]
                      openshift.io/scc: restricted
Status:               Running
IP:                   10.131.0.19
IPs:
  IP:           10.131.0.19
Controlled By:  ReplicaSet/cluster-56c87cf765
Containers:
  openshift-descheduler:
    Container ID:  cri-o://64be5474c329fa3cad7b993384e68c130e1af59e63164bba22c04751c4dd3e95
    Image:         quay.io/jchaloup/descheduler:debug-20200401
    Image ID:      quay.io/jchaloup/descheduler@sha256:4bdbe9352139e2f8494311e7440f6d934d4bd5ef22a298493f3bc7c6b6b5cca3
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/descheduler
    Args:
      --policy-config-file=/policy-dir/policy.yaml
      --v=5
      --descheduling-interval=3600s
    State:          Running
      Started:      Wed, 01 Apr 2020 19:08:48 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  500Mi
    Requests:
      cpu:        100m
      memory:     500Mi
    Environment:  <none>
    Mounts:
      /policy-dir from policy-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from openshift-descheduler-token-f58mr (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  policy-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      cluster
    Optional:  false
  openshift-descheduler-token-f58mr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  openshift-descheduler-token-f58mr
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age        From                                                 Message
  ----    ------     ----       ----                                                 -------
  Normal  Scheduled  <unknown>  default-scheduler                                    Successfully assigned openshift-kube-descheduler-operator/cluster-56c87cf765-jpqh4 to ip-10-0-171-235.us-east-2.compute.internal
  Normal  Pulling    104s       kubelet, ip-10-0-171-235.us-east-2.compute.internal  Pulling image "quay.io/jchaloup/descheduler:debug-20200401"
  Normal  Pulled     99s        kubelet, ip-10-0-171-235.us-east-2.compute.internal  Successfully pulled image "quay.io/jchaloup/descheduler:debug-20200401"
  Normal  Created    98s        kubelet, ip-10-0-171-235.us-east-2.compute.internal  Created container openshift-descheduler
  Normal  Started    98s        kubelet, ip-10-0-171-235.us-east-2.compute.internal  Started container openshift-descheduler
```

Descheduler seems to be running:
```
$ oc logs cluster-56c87cf765-jpqh4 -n openshift-kube-descheduler-operator
I0401 17:08:48.569741       1 node.go:44] node lister returned empty list, now fetch directly
I0401 17:08:48.656173       1 duplicates.go:50] Processing node: "ip-10-0-128-246.us-east-2.compute.internal"
I0401 17:08:48.758090       1 duplicates.go:50] Processing node: "ip-10-0-134-192.us-east-2.compute.internal"
I0401 17:08:48.859375       1 duplicates.go:50] Processing node: "ip-10-0-149-67.us-east-2.compute.internal"
I0401 17:08:49.052030       1 duplicates.go:50] Processing node: "ip-10-0-157-182.us-east-2.compute.internal"
I0401 17:08:49.075693       1 duplicates.go:50] Processing node: "ip-10-0-160-251.us-east-2.compute.internal"
I0401 17:08:49.158216       1 duplicates.go:50] Processing node: "ip-10-0-171-235.us-east-2.compute.internal"
I0401 17:08:49.678736       1 lownodeutilization.go:145] Node "ip-10-0-157-182.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":86.8, "memory":40.09200470623151, "pods":5.2}
I0401 17:08:49.678794       1 lownodeutilization.go:150] allPods:13, nonRemovablePods:13, bePods:0, bPods:0, gPods:0
I0401 17:08:49.678961       1 lownodeutilization.go:145] Node "ip-10-0-160-251.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":50.628571428571426, "memory":29.550577210328083, "pods":12.4}
I0401 17:08:49.678990       1 lownodeutilization.go:150] allPods:31, nonRemovablePods:30, bePods:0, bPods:1, gPods:0
I0401 17:08:49.679097       1 lownodeutilization.go:145] Node "ip-10-0-171-235.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":85.46666666666667, "memory":44.05371887686421, "pods":7.6}
I0401 17:08:49.679121       1 lownodeutilization.go:150] allPods:19, nonRemovablePods:14, bePods:1, bPods:4, gPods:0
I0401 17:08:49.679193       1 lownodeutilization.go:145] Node "ip-10-0-128-246.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":86.8, "memory":37.97547247808529, "pods":4.8}
I0401 17:08:49.679215       1 lownodeutilization.go:150] allPods:12, nonRemovablePods:12, bePods:0, bPods:0, gPods:0
I0401 17:08:49.679374       1 lownodeutilization.go:145] Node "ip-10-0-134-192.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":52.05714285714286, "memory":33.10105217442801, "pods":14.8}
I0401 17:08:49.679398       1 lownodeutilization.go:150] allPods:37, nonRemovablePods:37, bePods:0, bPods:0, gPods:0
I0401 17:08:49.752101       1 lownodeutilization.go:145] Node "ip-10-0-149-67.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":49.48571428571429, "memory":28.12520404955804, "pods":11.6}
I0401 17:08:49.752456       1 lownodeutilization.go:150] allPods:29, nonRemovablePods:28, bePods:0, bPods:1, gPods:0
I0401 17:08:49.752475       1 lownodeutilization.go:66] Criteria for a node under utilization: CPU: 10, Mem: 20, Pods: 30
I0401 17:08:49.752489       1 lownodeutilization.go:70] No node is underutilized, nothing to do here, you might tune your thresholds further
```

**Pull request merged**
